name: Clone to dev_repo

on:
  push:
    branches:
      - release

jobs:
  clone_to_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push from release to dev branch.
        uses: Automattic/action-commit-to-branch@master
        with:
          dest_branch: 'dev_repo'
          source_branch: 'release'
          commit_message: 'Automated tests for main.'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
