name: PR create

on:
  push:
    branches:
      - main


jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: python .github/workflows/create_pull_request.py ${{ secrets.PAT_TOKEN }}
