name: Databricks job

on:
  workflow_dispatch:
    inputs:
      # env:
      SOURCE_ENV: dev,test,prod
      TARGET_ENV: test
      DATABRICKS_API_TOKEN: 


jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    env:
      SOURCE_ENV: ${{ github.event.inputs.SOURCE_ENV }}
      TARGET_ENV: test
      DATABRICKS_API_TOKEN: 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
  
      - name: Call Databricks API
        run: |
          python .github/workflows/apicall.py
